branchProtectionRules:
 # List of required status check contexts that must pass for commits to be accepted to matching branches.
  requiredStatusCheckContexts:
    - 'Samples - Python 3.6'
    - 'Samples - Python 3.7'
    - 'Samples - Python 3.8'
    - 'Samples - Lint'
